### ISSUE TITLE
默认的UUID是否需要更改？

### ISSUE THREAD

**Issue by lanyun1973** [Misaka-blog/xray-for-paas#5]
de04add9-5c68-8bab-950c-08cd5320df18这个默认值是否需要更改成新生成的UUID？
[Warning] [2532649263] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://65329898.xyz/vmess): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed

**Comment by sepehrrostami** [comment]
Hi. You can change the UUID if you want or use the default.
About that warning, it seems that something is wrong with your configuration. for WebSocket
Are you using a custom domain? Maybe the WebSocket feature is off in your setting

**Comment by Misaka-blog** [comment]
UUID的话如无问题可以不用修改
